sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3
  - hhvm
  - nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  allow_failures:
    - php: nightly

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
  matrix:
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - DEPENDENCIES=""

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update -o --prefer-source $COMPOSER_ARGS $DEPENDENCIES
  - composer show

script:
 - php ./vendor/bin/phpunit --configuration tests/phpunit.xml
